version: "3.3"

services:
  frontend:
    build: frontend
    restart: always
    links:
      - backend
    ports:
      - "3000:3000"

  backend:
    build: backend
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8000:8000"
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_DB_UPLOAD: ${MONGO_DB_UPLOAD}
      EMAIL: ${EMAIL}
      MAILPASSWORD: ${MAILPASSWORD}

  mongo:
    image: mongo
    ports:
      - "27107:27107"
